---
rke2_windows_group_name: "windows"

rke2_token: "defaultSecret12345"

rke2_architecture: amd64

rke2_version: "v1.25.3+rke2r1"

kube_version: "{{ rke2_version.split('+')[0] }}"

node_taints:
  - "os=windows/NoSchedule"

service_cidr: "10.42.0.0/16"

dns_server_ip: "10.42.0.10"

rke2_airgap_mode: false

# airgap install tarball copy source
rke2_airgap_copy_sourcepath: local_artifacts

# airgap install tarball copy destination
rke2_tarball_images_path: C:\var\lib\rancher\rke2\agent\images
