---

- name: Deploy RKE2
  hosts: k8s_cluster
  become: yes
  vars:
    rke2_cni: calico
    rke2_token: defaultSecret12345
    rke2_ha_mode: true
    # rke2_api_ip: 
  roles:
    - role: lablabs.rke2

- name: Deploy windows
  hosts: windows
  vars:
    rke2_token: defaultSecret12345
  roles:
    - role: win.rke2