- name: mkdir rke2
  win_file:
    path: C:\etc\rancher\rke2
    state: directory

- name: copy config
  win_copy:
    content: |
      server: https://{{ hostvars[groups['masters'].0]['ansible_default_ipv4']['address'] }}:9345
      token: {{ rke2_token }}
    dest: C:\etc\rancher\rke2\config.yaml

- name: download rke2 install script
  win_get_url:
    url: https://raw.githubusercontent.com/rancher/rke2/master/install.ps1
    dest: .\install.ps1
  when: not rke2_airgap_mode

- name: copy airgap artifacts
  block:
  - name: create airgap directory
    win_file:
      path: "{{ rke2_tarball_images_path }}"
      state: directory
    when: rke2_airgap_mode
  - name: copy rke2 windows artifacts
    win_copy:
      src: "{{ rke2_airgap_copy_sourcepath }}/{{ item }}"
      dest: "{{ rke2_tarball_images_path }}/{{ item }}"
    with_items:
    - "rke2.windows-{{ rke2_architecture }}.tar.gz"
    - "rke2-windows-ltsc2022-{{ rke2_architecture }}-images.tar.gz"
    - "sha256sum-{{ rke2_architecture }}.txt"
  - name: copy rke2 powershell install script
    win_copy:
      src: "{{ rke2_airgap_copy_sourcepath }}/install.ps1"
      dest: .\install.ps1
  when: rke2_airgap_mode

- name: add bin to path
  win_path:
    elements:
    - 'c:\var\lib\rancher\rke2\bin'
    - 'c:\usr\local\bin'

- name: Run install script
  ansible.windows.win_powershell:
    script: |
      .\install.ps1 -Version '{{ rke2_version }}' -Type agent {% if rke2_airgap_mode %}-ArtifactPath '{{ rke2_tarball_images_path }}'{% endif %}

- name: install agent
  ansible.windows.win_powershell:
    script: |
      rke2.exe agent service --add
  register: script_return

- name: start rke2 service
  win_service:
    name: rke2
    start_mode: auto
    state: started